### ISSUE TITLE
Getting Error while starting zookeepr-server

### ISSUE THREAD

**Issue by salmanmal** [krunalvora/kafka-workshop#1]
![Screenshot 2020-03-02 at 11 54 02 PM](https://user-images.githubusercontent.com/38141342/75754249-3da76900-5ce1-11ea-925b-d19756b13373.png)
Getting the following error, while starting zookeeper-server from terminal,
_Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.quorum.QuorumPeerMain_

**Comment by krunalvora** [comment]
@salmanmal could you verify your java version?

**Comment by salmanmal** [comment]
@krunalvora 
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

**Comment by krunalvora** [comment]
@salmanmal could you try the docker-compose version?
